### ISSUE TITLE
Retry

### ISSUE THREAD

**Issue by lzanol** [sambatech/player_sdk_ios#33]
### Tasks
- [x] Interceptar erro
- [x] Timer
- [x] Feedback
- [x] Reconexão
- [x] Erro final
- [x] (NTH) Botão "retry"
- [x] Testes
  - [x] Ao interromper conexão, contar N segs e tentar mais 2 vezes e falhar
  - [x] Ao interromper conexão, contar N segs e reconectar
  - [ ] Ao carregar mídia
  - [ ] Durante a reprodução

### Done
Player reconectando até 3 vezes em caso de falha **durante** a reprodução ou falhando permanentemente.

**Comment by lzanol** [comment]
### Deploy
- [ ] Release (v0.5.0 + release notes)

**Comment by lzanol** [comment]
### Docs
#### Códigos de erro
Código|Descrição|Criticalidade
-|-|-
-1|Crítico|Erro desconhecido
1|Crítico|O formato da URL é inválido
2|Crítico|Erro ao criar o player interno
3|Crítico|Reprodução de mídia segura em dispositivo desbloqueado (rooted)
4|Crítico|Player interno não carregado

Para demais erros, por favor consulte a [lista de erros oficial](https://developer.apple.com/reference/foundation/foundation_constants#//apple_ref/doc/constant_group/URL_Loading_System_Error_Codes) fornecida pela Apple e no [Stackoverflow](http://stackoverflow.com/a/9415479/3688598) para alguns erros não documentados pela Apple.

Criticalidade|Comportamento
Crítico|O player será destruído e exibida uma mensagem de erro
Recuperável|O player será destruído, mas tentará se recuperar
Mínimo|O player tentará prosseguir normalmente com a reprodução

**Comment by priscilamagalhaes** [comment]
### BUGs

- [ ] Live - Não está iniciando o vídeo após reconectar.
- [ ] VOD DRM - Não inicia o vídeo após reconectar (não sei se deveria)
  **Passos**
 - Acessar vídeo DRM.
 - Iniciar o vídeo e retirar a conexão a internet.
 - Aguardar o dispositivo bloquear.
 - Desbloquear o dispositivo.
   - Verificar que a mensagem é apresentada corretamente.
 - Reconectar a internet e clicar em Tente novamente.
   - Irá apresentar a mensagem de erro.
